language: python
python:
  - 2.7
env:
  - DJANGO=1.4.0
  - DJANGO=1.4.5
  - DJANGO=1.5
  - DJANGO=1.6
before_install:
  - export DJANGO_SETTINGS_MODULE=s3direct.tests.settings
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install mock
script:
  - python manage.py test s3direct